export interface Solicitudesusuario{
    "solicitudes_num_solicitud": number,
        "solicitudes_usuario": number,
        "solicitudes_id_oferta_trabajo": number,
        "solicitudes_estado": string,
        "solicitudes_visible_empresa": boolean,
        "solicitudes_visible_usuario": boolean,
        "oferta_trabajos_num": number,
        "oferta_trabajos_titulo": string,
        "oferta_trabajos_descripcion": string,
        "oferta_trabajos_popularidad": boolean,
        "oferta_trabajos_anuncio": boolean,
        "oferta_trabajos_visible_usuario": boolean,
        "oferta_trabajos_visible_empresa": boolean,
        "oferta_trabajos_num_empresa": number,
        "oferta_trabajos_categoria": number,
        "oferta_trabajos_ciudad": number,
        "oferta_trabajos_fecha_publicacion": string,
        "usuarios_nombre": string,
        "usuarios_apellido": string,
        "usuarios_descripcion": string,
        "usuarios_telefono": string,
        "usuarios_direccion": string,
        "usuarios_foto": string,
        "usuarios_fecha_nacimiento": string,
        "usuarios_token": string
}